name: hugo_deploy

on:
  # push 或 pull request 到 main 时启动
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # 手动启动
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1.Checkout
        uses: actions/checkout@v4
        with:
          submodules: true  # clone 主题
          fetch-depth: 0

      - name: 2.Setup Go environment
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.3

      - name: 3.Hugo setup
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true

      - name: 4.Build
        run: hugo --minify

      - name: 5.Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
